let shopItemsData = [
  {
    id: "id1",
    name: "Casual Shirt",
    price: 75,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img1.jpg",
  },
  {
    id: "id2",
    name: "Suit Mans",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img2.jpg",
  },
  {
    id: "id3",
    name: "Tie Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img6.jpg",
  },
  {
    id: "id4",
    name: "Fashion Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img4.jpg",
  },
  {
    id: "id5",
    name: "T - Shirt",
    price: 80,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img5.jpg",
  },
  {
    id: "id6",
    name: "Scirt Off",
    price: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img7.jpg",
  },
  {
    id: "id7",
    name: "Tie Suit",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img3.jpg",
  },
  {
    id: "id8",
    name: "Fashion Suit",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "imges/img8.jpg",
  },
];
